ARG GO_VERSION=1.23.5
FROM golang:${GO_VERSION}-alpine

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the application 
ARG TARGETARCH
RUN CGO_ENABLED=0 GOARCH=${TARGETARCH} go build -o /bin/server .

# Giving permission
RUN chmod +x /bin/server

# Expose the port
EXPOSE 8080

# Run the application
CMD ["/bin/server"]

